#!/bin/bash


if git diff --name-only --cached | grep '\.rb$'
then
  echo "Running rubocop for added ruby files..."
  git diff --name-only --cached | grep '\.rb$' | xargs docker-compose run app bundle exec rubocop
fi
