version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk-s3
    versions:
    - 1.87.0
    - 1.88.1
    - 1.88.2
    - 1.89.0
    - 1.90.0
    - 1.92.0
    - 1.93.0
    - 1.93.1
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: rubocop-performance
    versions:
    - 1.10.1
    - 1.10.2
  - dependency-name: bootsnap
    versions:
    - 1.7.1
    - 1.7.3
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 5.0.0
  - dependency-name: rails
    versions:
    - 6.0.3.4
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: rubocop-rails_config
    versions:
    - 1.2.1
    - 1.3.0
    - 1.3.1
    - 1.3.2
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
