inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
